reg delete "HKLM\SOFTWARE\Microsoft\TouchPrediction" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ApplicationServiceElastic" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ApplicationServiceHighPriElastic" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ApplicationServiceHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ApplicationServiceRemote" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\AppToAppTarget" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\BackgroundAudioPlayer" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\BackgroundCachedFileUpdater" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\BackgroundTaskCompletion" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\BackgroundTaskDebug" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\BackgroundTransfer" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\BackgroundTransferNetworkState" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\Balloon" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\CalendarProviderAsChild" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\CallingEvent" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ContinuousBackgroundExecution" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\CortanaSpeechBackground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\CreateProcess" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\DefaultModernBackgroundTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\DefaultPPLE" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\EmCreateProcess" /v "CPU" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\EmCreateProcessNormalPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\EmptyHost" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\EmptyHostHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\FileProviderTarget" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ForegroundAgent" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ForegroundCachedFileUpdater" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ForegroundTaskCompletion" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\Frozen" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\GenericExtendedExecution" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\GeofenceTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\HighPriorityBackgroundAgent" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\HighPriorityBackgroundDemoted" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\HighPriorityBackgroundTransfer" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\IoTStartupTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\JumboForegroundAgent" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaBackgroundTaskCompletion" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaDefaultModernBackgroundTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaPrelaunchForeground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiDebugModeForeground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiFrozen" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiFrozenDNCS" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiFrozenDNK" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiFrozenHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiModernForeground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiModernForegroundLarge" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiPaused" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiPausedDNK" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiPausedHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LmaUiPausing" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LongRunningBluetooth" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LongRunningControlChannel" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\LongRunningSensor" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\MediaProcessing" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\OemBackgroundAgent" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\OemTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\PendingDefaultPPLE" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\PiP" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\PreinstallTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\PrelaunchForeground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\PushTriggerTask" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ResourceIntensive" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ShareDataPackageHost" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\ShortRunningBluetooth" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\TaskCompletionHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiComposer" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiDebugModeForeground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiForegroundDNK" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiFrozen" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiFrozenDNCS" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiFrozenDNK" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiFrozenHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiLockScreen" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiModernForeground" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiModernForegroundExtended" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiModernForegroundLarge" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiOverlay" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiPaused" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiPausedDNK" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiPausedHighPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiPausing" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiPausingLowPriority" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiShellCustom1" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiShellCustom2" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiShellCustom3" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\PolicySets\UiShellCustom4" /v "Importance" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\HardCap0" /v "CapPercentage" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\HardCap0" /v "SchedulingType" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\Paused" /v "CapPercentage" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\Paused" /v "SchedulingType" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\SoftCapFull" /v "CapPercentage" /f
reg delete "HKLM\SYSTEM\ResourcePolicyStore\ResourceSets\Policies\CPU\SoftCapFull" /v "SchedulingType" /f
